apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: jonasborgeslm/gitops
  newTag: ba6c8ab37d3449b74b05c63b2151c294afbd9794
