apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: jonasborgeslm/gitops
  newTag: bbf40516275664191c9db0e898d057a5fb8df17d
